language: python
python:
    - "3.6"
    - "3.7"
before_install:
    # Here, we install the stuff needed to test the q2-qurro plugin.
    # This will cause tests to take a while, but that's an ok price to pay.
    #
    # 1. Install conda (commands from
    # https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/use-conda-with-travis-ci.html)
    - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    - conda info -a
    # 2. Install the latest QIIME 2 version
    # (see https://dev.qiime2.org/latest/quickstart, thanks @thermokarst for
    # the heads up :)
    - wget https://raw.githubusercontent.com/qiime2/environment-files/master/latest/staging/qiime2-latest-py36-linux-conda.yml
    - travis_retry conda env create -n qiime2-dev --file qiime2-latest-py36-linux-conda.yml
    - source activate qiime2-dev
    # 3. Install Songbird and DEICODE
    # (this will let us rerun the corresponding example notebooks)
    - conda install -c conda-forge songbird deicode
    # 4. Install seaborn so we can run the colors example notebook
    # (should be already installed in a QIIME 2 environment, but we may as well
    # make sure that this won't break in the future)
    - conda install seaborn
    # 5. Install ALDEx2 and mygene
    # (this will let us rerun the ALDEx2 example notebook)
    - conda install -c bioconda bioconductor-aldex2 mygene
install:
    - pip install -e .[dev]
    # Install various JS testing/stylechecking packages that we use for
    # developing qurro, but aren't required to just use qurro
    - npm install -g mocha-headless-chrome
    - npm install -g jshint
    - npm install -g prettier
    - npm install -g nyc
script:
    # Just to be safe
    - qiime dev refresh-cache
    # Run actual Qurro tests (both Python and JavaScript)
    - make test
    # Verify that example notebooks can be run without crashing
    - make notebooks
    # Verify that code is properly formatted
    - make stylecheck
after_success:
    - wget -O codecov.sh https://codecov.io/bash
    # Upload coverage information (see
    # https://docs.codecov.io/docs/merging-reports). Fortunately, codecov's
    # bash script detects both the python and JS code coverage by default --
    # so it automatically merges the reports, without us needing to run
    # codecov.sh multiple times (although that should be doable also, in case
    # future reports aren't automatically detected).
    - bash codecov.sh -c
